name: homebot-auto-tag
concurrency: autotag
on:
  push:
    branches:
      - 'main'
jobs:
  test-and-tag: #from https://medium.com/@AranT/auto-tagging-and-using-semantic-versioning-with-github-actions-e40188d12cf4
    name: "tag"
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      next-tag: ${{ steps.taggerFinal.outputs.new_tag }}
      increment: ${{ steps.taggerFinal.outputs.part }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Auto-tag dry-run
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: none
      - name: echo tag information
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
          echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - name: Test
        run: go test -v ./...
      - name: Auto-tag
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none

  build-armv6l:
    needs: [ "tag" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Read output
        run: echo ${{needs.tag.outputs.next-tag}} ${{needs.tag.outputs.increment}}
#      - uses: pguyot/arm-runner-action@v2
#        id: build_image
#        with:
#          image_additional_mb: 2048
#          base_image: raspios_lite:latest
#          cpu: arm1176
#          cpu_info: cpuinfo/raspberrypi_zero_w
#          commands: |
#            GO_URL=https://go.dev/dl/
#            export GOLANG="$(curl $GO_URL |grep linux-armv6l |grep -v beta |head -1 |awk -F\> {'print $3'}|awk -F\< {'print $1'})"
#            wget $GO_URL$GOLANG
#            sudo tar -C /usr/local -xzf $GOLANG
#            rm $GOLANG
#            unset GOLANG
#            export PATH=$PATH:/usr/local/go/bin
#            make clean build